language: python
python:
  - "2.7"

install:

    # command to install dependencies
    - python setup.py install

script:

    # command to run tests. they dont currently run on travis since we dont have an openstack environment available
    # from there
    # - nosetests --nocapture