language: python
python:
  - "2.7"

install:

    # command to install dependencies
    - python setup.py install

script:

    - flake8 .
    # command to run tests. they don't currently run on travis since we dont have an openstack environment available
    # from there
    - echo no tests